name: cinetracker
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  uuid: ^4.5.2
  iconsax: ^0.0.8
  provider: ^6.1.5+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  #since we are storing objects , we use both hive_generator and build_runner

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/cineIcon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/cineIcon.png
  min_sdk_android: 21

flutter_native_splash:
  color: "#0F172A"
  image: assets/cineIcon.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFit
